package task;

import util.Parser;

import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import static java.time.format.DateTimeFormatter.ISO_LOCAL_DATE;

/**
 * Type of Task that stores an event and the date which the event occurs.
 */
public class Event extends Task {
    public static final String COMMAND_STRING = "event";
    public static final String EVENT_DATE_STRING = "at";
    private final LocalDate eventDate;

    /**
     * Constructs an Event with the supplied description and time.
     *
     * @param desc String description of the Event.
     * @param eventDate LocalDate object representing the date the Event occurs.
     */
    public Event(String desc, LocalDate eventDate) {
        super(desc);
        this.eventDate = eventDate;
    }

    /**
     * Overloaded constructor to create an Event with the supplied description,
     * date and completion status.
     * @param desc String description of the Event.
     * @param eventDate LocalDate object representing the date the Event occurs.
     * @param isDone True, if the Event should be initialised as done.
     */
    public Event(String desc, LocalDate eventDate, boolean isDone) {
        super(desc, isDone);
        this.eventDate = eventDate;
    }

    /**
     * Parses the saveString generated by toSaveString() back into an Event
     * object.
     *
     * @param saveString String representation of a Event object.
     * @return Event object based on the supplied saveString.
     */
    public static Event fromSaveString(String saveString) throws IOException {
        HashMap<String, List<String>> commandMap = Parser.parseCommandMap(saveString);

        // Attempt to parse the description
        List<String> descriptions;
        String description;
        try {
            descriptions = commandMap.get(COMMAND_STRING);
            description = String.join(" ", descriptions);
        } catch (NullPointerException e) {
            throw new IOException("Description could not be parsed from: " + saveString);
        }

        // Attempt to parse the date from the saveString
        String eventDateString;
        LocalDate eventDate;
        try {
            eventDateString = commandMap.get(EVENT_DATE_STRING).get(0);
            eventDate = LocalDate.parse(eventDateString);
        } catch (NullPointerException | IndexOutOfBoundsException | DateTimeParseException e) {
            throw new IOException("Date could not be parsed from: " + saveString);
        }

        boolean isDone = commandMap.containsKey("done");

        return new Event(description, eventDate, isDone);
    }

    @Override
    public String toString() {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("E, d MMM yy");
        String dateString = eventDate.format(dateTimeFormatter);
        return "[E]" + super.toString() + " (at: " + dateString + ")";
    }

    @Override
    public TaskType getTaskType() {
        return TaskType.EVENT;
    }

    @Override
    public String getCommandString() {
        return COMMAND_STRING;
    }

    /**
     * Convert the Event, its state and variables to a String representation
     * that can be parsed to obtain back the same Event.
     *
     * @return String representation of the Event and its state.
     */
    @Override
    public String toSaveString() {
        HashMap<String, List<String>> commandMap = new HashMap<>();

        // Add command flag
        commandMap.put(Parser.COMMAND_FLAG, new ArrayList<>());
        commandMap.get(Parser.COMMAND_FLAG).add(getCommandString());

        // Add description
        commandMap.put(getCommandString(), new ArrayList<>());
        commandMap.get(getCommandString()).add(super.getDescription());

        // Add end date
        commandMap.put(EVENT_DATE_STRING, new ArrayList<>());
        commandMap.get(EVENT_DATE_STRING).add(eventDate.format(ISO_LOCAL_DATE));

        // Add done flag
        if (super.isDone()) {
            commandMap.put("done", new ArrayList<>());
        }

        return Parser.commandMapToString(commandMap);
    }
}
