import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;

/**
 * {@code Blarb} is the chat bot in used in the {@code Main} program.
 */
public class Blarb {
    private final List<Task> list;
    private final String filePath;

    /**
     * Initializes Blarb.
     */
    public Blarb() {
        list = new ArrayList<>(100);
        filePath = "data/tasklist.txt";
        try {
            File file = new File(filePath);
            File parent = file.getParentFile();
            parent.mkdirs();
            file.createNewFile();
            Scanner sc = new Scanner(file);
            while (sc.hasNextLine()) {
                String str = sc.nextLine();
                String[] tokens = str.split(" / ");
                Task task;
                switch (tokens[0]) {
                case "T":
                    task = new ToDo(tokens[2]);
                    if (Integer.parseInt(tokens[1]) == 1) {
                        task.markAsDone();
                    }
                    break;
                case "D":
                    task = new Deadline(tokens[2], tokens[3]);
                    if (Integer.parseInt(tokens[1]) == 1) {
                        task.markAsDone();
                    }
                    break;
                case "E":
                    task = new Event(tokens[2], tokens[3]);
                    if (Integer.parseInt(tokens[1]) == 1) {
                        task.markAsDone();
                    }
                    break;
                default:
                    throw new InputMismatchException();
                }
                list.add(task);
            }
        } catch (IOException ex) {
            warn("Cannot initialize task list file.");
        } catch (InputMismatchException ex) {
            warn("File is corrupted. Cannot initialize task list.");
        } finally {
            blurt("This is BLARB.\nYou may speak.");
        }
    }

    /**
     * Prints output in response format.
     *
     * @param output Output string
     */
    private void blurt(String output) {
        String response = "%s\n\n> ";
        System.out.printf(response, output);
    }

    /**
     * Prints an error message generated by exceptions not caused by user input.
     *
     * @param warn The warning message to be displayed.
     */
    private void warn(String warn) {
        String response = "Error! %s\n\n";
        System.err.printf(response, warn);
    }

    /**
     * Prints the task list.
     */
    private void list() {
        if (list.size() < 1) {
            blurt("You have nothing on your list.");
        } else {
            int i = 1;
            StringBuilder sb = new StringBuilder("Here are your tasks:\n");
            for (Task task : list) {
                sb.append(String.format("\n%d. %s", i++, task.toString()));
            }
            blurt(sb.substring(0));
        }
    }

    /**
     * Changes the indexed task to a completed state.
     *
     * @param index The index of the task.
     */
    private void done(int index) {
        try {
            list.get(index).markAsDone();
            String done = "I've marked this task as done:\n%s";
            try {
                refile();
            } catch (IOException ex) {
                warn(ex.getMessage());
            }
            blurt(String.format(done, list.get(index)));
        } catch (IndexOutOfBoundsException ex) {
            blurt("There is no such task.");
        }
    }

    /**
     * Delete the indexed task.
     *
     * @param index The index of the task.
     */
    private void delete(int index) {
        try {
            String delete = "The task is terminated:\n%s";
            Task output = list.get(index);
            list.remove(index);
            try {
                refile();
            } catch (IOException ex) {
                warn(ex.getMessage());
            }
            blurt(String.format(delete, output));
        } catch (IndexOutOfBoundsException ex) {
            blurt("There is no such task.");
        }
    }

    /**
     * Adds a new Task to the task list.
     *
     * @param task Task to be added.
     */
    private void add(Task task) {
        String addTask = "Affirmative. I've added this task:\n %s\n"
                + "Now you have %d tasks in the list.";
        list.add(task);
        try {
            file(task);
        } catch (IOException ex) {
            warn(ex.getMessage());
        }
        blurt(String.format(addTask, task.toString(), list.size()));
    }

    /**
     * Appends a task to the tasklist file.
     *
     * @param task Task to be added.
     * @throws IOException Issues with writing into the file.
     */
    private void file(Task task) throws IOException {
        FileWriter fw = new FileWriter(filePath, true);
        fw.write(task.encode());
        fw.write("\n");
        fw.close();
    }

    /**
     * Rewrites the entire tasklist file.
     *
     * @throws IOException Issues with writing into the file.
     */
    private void refile() throws IOException {
        FileWriter fw = new FileWriter(filePath);
        for (Task task : list) {
            fw.write(task.encode());
            fw.write("\n");
        }
        fw.close();
    }

    /**
     * Parses and determines course of action for Blurb.
     *
     * @param input The inputted command.
     * @return A boolean value that shows the availability for the next command intake.
     */
    public boolean execute(String input) {
        if (input.equalsIgnoreCase("bye")) {
            System.out.println("Hasta la vida, baby.");
            return false;
        }

        //Splits the input into two parts -- the command and the description.
        String[] tokens = input.split(" ", 2);

        //Calls method and handles exception according to command
        switch (Command.command(tokens[0])) {
        case DONE:
            try {
                int idx = Integer.parseInt(tokens[1]) - 1;
                done(idx);
            } catch (ArrayIndexOutOfBoundsException ex) {
                blurt("What have you done! More specific!");
            } catch (NumberFormatException ex) {
                blurt("Done what now? I don't understand");
            }
            break;
        case DELETE:
            try {
                int idx = Integer.parseInt(tokens[1]) - 1;
                delete(idx);
            } catch (ArrayIndexOutOfBoundsException ex) {
                blurt("What do you want to hide?");
            } catch (NumberFormatException ex) {
                blurt("You can't delete your past.");
            }
            break;
        case TODO:
            try {
                Task task = new ToDo(tokens[1]);
                add(task);
            } catch (ArrayIndexOutOfBoundsException ex) {
                blurt("Todo what?");
            }
            break;
        case DEADLINE:
            try {
                String[] fragments = tokens[1].split(" /by ");
                try {
                    Task task = new Deadline(fragments[0], fragments[1]);
                    add(task);
                } catch (ArrayIndexOutOfBoundsException ex) {
                    blurt("Type the deadline, then give the time using \"/by\".");
                }
            } catch (ArrayIndexOutOfBoundsException ex) {
                blurt("Someone's having trouble with deadlines.");
            }
            break;
        case EVENT:
            try {
                String[] fragments = tokens[1].split(" /at ");
                try {
                    Task task = new Event(fragments[0], fragments[1]);
                    add(task);
                } catch (ArrayIndexOutOfBoundsException ex) {
                    blurt("Type the event, then give the time using \"/at\".");
                }
            } catch (ArrayIndexOutOfBoundsException ex) {
                blurt("Tell me the event!");
            }
            break;
        case LIST:
            if (tokens.length == 1) {
                list();
            } else {
                blurt("Listing is simple, so typing \"list\" would suffice.");
            }
            break;
        default:
            blurt(String.format("I have detailed files on human anatomy, but not %s.", input));
        }

        return true;
    }
}

