package blarb;

import java.util.Scanner;

class Ui {
    private final Scanner sc;

    Ui() {
        sc = new Scanner(System.in);
    }

    public String read() {
        return sc.nextLine();
    }

    public boolean isAvailable() {
        return sc.hasNextLine();
    }

    public void rollCredits() {
        String logo = " ____            _      ____   ____\n" +
                "|    \\ |        / \\    |    \\ |    \\\n" +
                "|____/ |       /___\\   |____/ |____/\n" +
                "|    \\ |      /     \\  |  \\   |    \\\n" +
                "|____/ |____ /       \\ |   \\_ |____/\n";
        System.out.println("You are now in the presence of\n" + logo);
    }

    public void adios() {
        System.out.println("Hasta la vida, baby.");
    }

    /**
     * Prints output in response format.
     *
     * @param output Output string
     */
    public void blurt(String output) {
        String response = "%s\n\n> ";
        System.out.printf(response, output);
    }

    /**
     * Prints an error message generated by exceptions not caused by user input.
     *
     * @param warn The warning message to be displayed.
     */
    public void warn(String warn) {
        String response = "Error! %s\n\n";
        System.out.printf(response, warn);
    }
}
