package duke.task;

/**
 * Represents a task that happens at a specific location and/or date and time.
 */
public class Event extends Task {
    private final String at;

    public Event(String content, String at) {
        super(content);
        this.at = at;
    }

    public String getAt() {
        return at;
    }

    /**
     * Deserialize the given string to create an Event instance. The string should be generated by #getSerialized().
     *
     * @param str the string to deserialize from
     * @return the created Event instance
     * @see #getSerialized()
     */
    public static Event deserialize(String str) {
        String[] words = str.split(" \\| ");
        boolean isDone = Boolean.parseBoolean(words[1]);
        String content = words[2];
        String at = words[3];

        Event event = new Event(content, at);
        if (isDone) {
            event.markDone();
        }

        return event;
    }

    /**
     * Serialize the Event instance to a string where the Event instance can be recreated from.
     *
     * @return the serialized Event instance
     */
    @Override
    public String getSerialized() {
        return String.format("E | %s | %s | %s", getIsDone(), getContent(), at);
    }

    @Override
    public String toString() {
        return String.format("[E][%s] %s (at: %s)", getStatusIcon(), getContent(), at);
    }
}
